name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Login to Docker Hub
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - name: Pull Docker image
      run: sudo docker pull dimasichiro/backend-magang
    - name: Delete Old docker container
      run: sudo docker rm -f backend-magang-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name backend-magang-container dimasichiro/backend-magang