name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $davidocta154 -p $senyumboyolali

    - name: Build the Docker image
      run: docker build -t backend-magang .
    - name: Push to Dockerhub
      run: docker push davidocta154/backend-magang:latest
