name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t backend-magang .
    - name: Push to Dockerhub
      run: docker push davidocta154/backend-magang:latest
